### ISSUE TITLE
selection of handles on version and CHECKSUM

### ISSUE THREAD

**Issue by cookie33** [EUDAT-B2SAFE/B2HANDLE-Migration#10]
The code has:
```
                # We assume that every valid old EUDAT record has a CHECKSUM entry
                # This also causes ignoring typical administrative Handles
                if helper_value.get("EUDAT/PROFILE_VERSION") == "1" or not "CHECKSUM" in helper_value:
                    continue
```
It only skips if there is a `EUDAT/PROFILE_VERSION` or if there is NO `CHECKSUM`. But what if there is a CHECKSUM and it is NOT a B2SAFE handle.

Do we only modify b2SAFE handles or also handles for for instance B2SHARE. And what if a customer uses the prefix besides an EUDAT project?

Do we have to check for for instance `irods://` in the URL?

So has the check to be extended?

**Comment by cookie33** [comment]
And what about the `10320/LOC` field. Is that used by B2SAFE only?

**Comment by TobiasWeigel** [comment]
We can also use a condition on whether 10320/LOC is present. Will this cover all B2SAFE Handles? I guess noone else (e.g. B2SHARE) uses 10320/loc, but I am not entirely sure.
