### ISSUE TITLE
migration fails if 10320/LOC field does not have a valid URL filled in

### ISSUE THREAD

**Issue by cookie33** [EUDAT-B2SAFE/B2HANDLE-Migration#7]
Hi,

testing it shows an other error:
```
fixedcontent = FALSE
Migration started: 2017-02-28 15:56:50.335267
Total number of Handles collected: 500000
Traceback (most recent call last):
  File "/home/handle1/git/B2HANDLE-Migration/b2handle-migration/migrationtool.py", line 316, in <module>
    migration_tool.execute()
  File "/home/handle1/git/B2HANDLE-Migration/b2handle-migration/migrationtool.py", line 52, in execute
    self.migrate_handles()
  File "/home/handle1/git/B2HANDLE-Migration/b2handle-migration/migrationtool.py", line 251, in migrate_handles
    raise Exception("Broken 10320/LOC record on %s: href on id 0 does not match Handle's URL value!" % handle_name)
Exception: Broken 10320/LOC record on 11230/0017ec92-d946-11e3-873a-d89d6771dd88: href on id 0 does not match Handle's URL value!
```
This is correct but it should not fail.
 
```
fixedcontent = FALSE
Migration started: 2017-02-28 15:57:04.987679
Total number of Handles collected: 500000
1%
Migration estimated to take 0:11:06.298800 - expected to finish at 2017-02-28 16:08:11.711907
2%
Traceback (most recent call last):
  File "/home/handle1/git/B2HANDLE-Migration/b2handle-migration/migrationtool.py", line 316, in <module>
    migration_tool.execute()
  File "/home/handle1/git/B2HANDLE-Migration/b2handle-migration/migrationtool.py", line 52, in execute
    self.migrate_handles()
  File "/home/handle1/git/B2HANDLE-Migration/b2handle-migration/migrationtool.py", line 251, in migrate_handles
    raise Exception("Broken 10320/LOC record on %s: href on id 0 does not match Handle's URL value!" % handle_name)
Exception: Broken 10320/LOC record on 11230/324fb066-aa1e-11e3-94bb-d89d6771dd88: href on id 0 does not match Handle's URL value!
```
This is correct but it should not fail.

**Comment by cookie33** [comment]
It would be nice if the tool than supplied the URL itself and gave a warning that it did so.

**Comment by TobiasWeigel** [comment]
It felt not right to me to decide on the URL field at this point when I wrote this - I would not have liked to take some decisions on B2SAFE's behalf that are dubious. So if you say that it is fine in these cases, then I believe it is ok to have the tool warn and fill the URL in regardless.

**Comment by cookie33** [comment]
I would opt for the tool filling in the URL and give a warning as stated. +1

**Comment by TobiasWeigel** [comment]
I'm fine with continuing with a warning rather than an exception. But the question is how the script should use the offending value in 10320/loc.

The assumption is that the 10320/loc always points in its first entry to the same address that is in the URL field. So if the 10320/loc has as its first entry a value that differs from the URL, what should happen?
a)
Just remove the first entry in 10320/loc. The address will thus not be present in the entire record anymore, essentially dropping out of the system. Is this dangerous?
b)
Leave the entry in 10320/loc and write it into EUDAT/REPLICA together with possible other 10320/loc values. Then, the resulting record will have a URL entry and a EUDAT/REPLICA entry with differing addresses - so this will look OK, but I am not sure whether the address given in that EUDAT/REPLICA first entry will be valid.

Also: These records are currently broken - so we are probably unlikely to find an automated solution that fixes them without doing something manually.

**Comment by cookie33** [comment]
Hi,

The code still seems not up to date.

If `10320/LOC` is:
```
URL
second PID
```
It will write the second second PID in EUDAT/REPLICA

If `10320/LOC` is:
```
second PID
```
It will write nothing to EUDAT/REPLICA
This because of the line:
```
del replica_locs[0]
```

Somehow this seems wrong.

I would like it to write the second PID to EUDAT/REPLICA

**Comment by cookie33** [comment]
I would modify it from:
```
                        # entry 0 should be the same as the Handle's base URL
                        if replica_locs.get(0) != helper_value["URL"]:
                            print("Warning: Broken 10320/LOC record on %s: href on id 0 does not match Handle's URL value!" % handle_name)
                        del replica_locs[0]
                        if replica_locs:
                            st_modify.append(MigrationTool.__modify_stmt(helper_index["10320/LOC"], "EUDAT/REPLICA", ",".join(replica_locs.itervalues())))
                        else:
                            st_remove.append(MigrationTool.__remove_stmt(handle_name, helper_index["10320/LOC"]))
```
to:
```
                        # entry 0 should be the same as the Handle's base URL
                        if replica_locs.get(0) != helper_value["URL"]:
                            print("Warning: Broken 10320/LOC record on %s: href on id 0 does not match Handle's URL value!" % handle_name)
                        else:
                              del replica_locs[0]
                        if replica_locs:
                            st_modify.append(MigrationTool.__modify_stmt(helper_index["10320/LOC"], "EUDAT/REPLICA", ",".join(replica_locs.itervalues())))
                        else:
                            st_remove.append(MigrationTool.__remove_stmt(handle_name, helper_index["10320/LOC"]))
```
This way it will delete the value in 0 only if it exists. And it will add all other values.
If the value in 0 is not the URL it will also add the values to EUDAT/REPLICA.
